---
author:  John Zlotek
name:	John Zlotek
output:
	pdf_document:
		keep_tex: true
geometry: margin=0.5in
fontsize: 10pt
urlcolor: blue
linkcolor: blue
header-includes: \usepackage{tabularx, hyperref, fontawesome, tabulary, color}
---
\pagenumbering{gobble}

# John Zlotek

\begin{center}
	\begin{tabularx}{\textwidth}{X X}
		\textcolor{Blue}{\faHome}: 4486 June Meadow Dr, Doylestown, PA 18902 \hfill&\hfill  \textcolor{Blue}{\faEnvelope}:  \href{mailto:jmz46@drexel.edu}{jmz46@drexel.edu } \\
		\textcolor{Blue}{\faPhone}:  215-527-0305 \hfill&\hfill \textcolor{Blue}{\faGithub}:  \href{https://www.github.com/jzlotek}{github.com/jzlotek}
	\end{tabularx}
\end{center}

___

#### Education

\begin{tabularx}{\textwidth}{l X}
	Drexel University 				 	 & \hfill Philadelphia, PA\\
	Bachelor and Master of Science in Computer Science 	 & \hfill Anticipated Graduation: June 2021\\
	Concentration in Computer Security, Minor in Mathematics & \hfill GPA: 3.80
\end{tabularx}

####  Honors and Awards

\begin{tabularx}{\textwidth}{l | l X}
	2016-present &  \textit{Dean's List} & \hfill Drexel University, Philadelphia PA\\
	2016 	     & \textit{Summa Cum Laude} & \hfill Central Bucks High School East, Doylestown PA\\
	2014 	     & \textit{Eagle Scout} & \hfill Boy Scouts of America, Troop 6, Doylestown PA\\
\end{tabularx}

#### Technical Skills

\begin{tabular}{l | l}
	Programming Languages & C++, Java, Python, Bash, HTML, JavaScript\\
	Operating Systems     & Windows, Linux (Arch and Ubuntu)\\
	Tools 		      & Maven, Git, SVN, MongoDB\\
	Frameworks 	      & OpenCV, Keras, Mule ESB, Spring, Jersey\\
	Software 	      & Visual Studio, Sourcetree, Microsoft Office, JetBrains Suite
\end{tabular}


#### Related Experience

\begin{tabularx}{\textwidth}{l X}
	\textbf{Penn Mutual Life Insurance} & \hfill Horsham, PA\\
	Software Developer Co-op 	    & \hfill September 2017 to March 2018
\end{tabularx}

\begin{list}{\quad}{}
	\item Developed and maintained REST API to integrate databases with other in-house services and endpoints
	\item Created machine learning application to parse information from hand written documents
\end{list}

&nbsp;

\begin{tabularx}{\textwidth}{l X}
	\textbf{Buckingham Pediatrics} & \hfill Buckingham, PA\\
	Technology Consultant 	       & \hfill February 2016 to present
\end{tabularx}

\begin{list}{\quad}{}
	\item Update and manage various forms of technology in the office by installing new drivers and software
	\item Update and maintain company website with accurate information and documents
\end{list}

#### Relevant Coursework
\begin{center}
	\begin{tabularx}{\textwidth}{ccc}
		Computer Programming I, II 	& Mathematical Foundations of Computer Science & Multivariate Calculus\\
		Advanced Programming Techniques & Computing and Informatics Design I, II, III & Linear Algebra\\
		Data Structures & Calculus I, II, III & Scientific Data Analysis \\
	\end{tabularx}
\end{center}
#### Teaching Assistant

\begin{tabularx}{\textwidth}{r | l X}
March to June 2018 & CS 172: \textit{Computer Programming II} & \hfill Drexel University, Philadelphia PA\\
  		   & \textit{Worked under Dr. Matthew Burlick}
\end{tabularx}
\begin{list}{\quad}
	\item Assisted with grading and monitoring students in multiple lab sections
	\item Tutored students in Cyber Learning Center
\end{list}

#### Activities

\begin{tabularx}{\textwidth}{l | X}
	2018 	     & Participant, Philly Codefest \hfill Drexel University, Philadelphia, PA\\
	2017 	     & Volunteer, GEAR UP \hfill West Philadelphia High School, Philadelphia, PA\\
	2016 to 2017 & Pep Band \hfill Drexel University, Philadelphia, PA
\end{tabularx}
